import os
import subprocess
from typing import List
from .config import Settings


def get_cert_name(domain: str, ssl_domains_list: List[str]) -> str:
    """
    Get the name of the certificate file generated by lego for a specific domain.
    Lego uses the first domain argument specified as the filename, replacing '*' with '_'.
    """
    domain_ssl_certs = [
        d for d in ssl_domains_list if d == domain or d.endswith(f".{domain}")
    ]
    if not domain_ssl_certs:
        # Fallback if no matching ssl domains were specified
        domain_ssl_certs = [domain, f"*.{domain}"]
    return domain_ssl_certs[0].replace("*", "_")


def obtain_certificates(settings: Settings) -> None:
    """
    Invoke lego command to obtain SSL certificates for all configured domains.
    """
    ssl_domains = settings.ssl_domains_list

    for domain in settings.domains_list:
        # Match ssl domains for this specific base domain
        domain_ssl_certs = [
            d for d in ssl_domains if d == domain or d.endswith(f".{domain}")
        ]
        if not domain_ssl_certs:
            # Fallback if no matching ssl domains were specified
            domain_ssl_certs = [domain, f"*.{domain}"]

        cert_name = domain_ssl_certs[0].replace("*", "_")
        cert_path = settings.working_dir / f".lego/certificates/{cert_name}.crt"
        key_path = settings.working_dir / f".lego/certificates/{cert_name}.key"

        if cert_path.exists() and key_path.exists():
            print(
                f"Certificate and key for {domain} already exist at {cert_path}. Skipping lego run."
            )
            continue

        print(
            f"Obtaining SSL Certificate for domain '{domain}' with SANs: {domain_ssl_certs}"
        )

        # Build lego command
        lego_cmd = [
            "lego",
            "run",
            "--email",
            settings.email,
            "--path",
            str(settings.working_dir / ".lego"),
            "--dns",
            "alidns",
            "--accept-tos",
        ]
        for d in domain_ssl_certs:
            lego_cmd.extend(["--domains", d])

        if settings.dry_run:
            print(f"[DRY RUN] Would execute lego command: {' '.join(lego_cmd)}")
            print(f"[DRY RUN] Creating mock certificate files for {domain}...")
            cert_path.parent.mkdir(parents=True, exist_ok=True)
            cert_path.write_text(
                "-----BEGIN CERTIFICATE-----\nMOCK CERTIFICATE DATA\n-----END CERTIFICATE-----\n"
            )
            key_path.write_text(
                "-----BEGIN RSA PRIVATE KEY-----\nMOCK PRIVATE KEY DATA\n-----END RSA PRIVATE KEY-----\n"
            )
            continue

        # Set credentials in the subprocess environment
        env = os.environ.copy()
        env["ALICLOUD_ACCESS_KEY"] = settings.aliyun_access_key_id
        env["ALICLOUD_SECRET_KEY"] = settings.aliyun_access_key_secret

        try:
            result = subprocess.run(
                lego_cmd, env=env, capture_output=True, text=True, check=True
            )
            print(f"Successfully obtained certificate for {domain}.")
            if result.stdout:
                print("Lego output:")
                print(result.stdout)
        except subprocess.CalledProcessError as e:
            print(f"Failed to run lego command for {domain}:")
            print("Exit code:", e.returncode)
            if e.stdout:
                print("stdout:", e.stdout)
            if e.stderr:
                print("stderr:", e.stderr)
            raise e
