name: Auto Renew and Deploy SSL Certificates

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 10 */2 *" # 每两个月的第十天执行一次

permissions:
  contents: write

jobs:
  renew-deploy-cert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@main

      - uses: tecolicom/actions-use-homebrew-tools@v1
        with:
          tools: lego

      - name: Obtain SSL Certificates
        env:
          DOMAINS: ${{ secrets.DOMAINS }}
          ALICLOUD_ACCESS_KEY: ${{ secrets.ALIYUN_ACCESS_KEY_ID }}
          ALICLOUD_SECRET_KEY: ${{ secrets.ALIYUN_ACCESS_KEY_SECRET }}
        run: |
          lego --email="${{ secrets.EMAIL }}" \
               --domains="${{ secrets.SSL_DOMAINS }}" \
               --path="${{ github.workspace }}/.lego" \
               --dns="alidns" \
               --accept-tos \
               run

      - name: Install Python dependencies
        run: pip install -r requirements.txt

      - name: Upload certificates to Alibaba Cloud CDN
        env:
          ALIYUN_ACCESS_KEY_ID: ${{ secrets.ALIYUN_ACCESS_KEY_ID }}
          ALIYUN_ACCESS_KEY_SECRET: ${{ secrets.ALIYUN_ACCESS_KEY_SECRET }}
          # 要设置域名的二级域名，例如要设置*.example.com，这里填写的就是example.com, 多个域名用英文逗号隔开
          DOMAINS: ${{ secrets.DOMAINS }}
          # 设置阿里云cdn域名，一般是三级域名，例如cdn.example.com，需要跟上面的DOMAINS对应，否则会设置错误
          ALIYUN_CDN_DOMAINS: ${{ secrets.ALIYUN_CDN_DOMAINS }}
          WORKING_DIR: ${{ github.workspace }}

        run: python upload_certs_to_aliyun.py

      - name: Clean up
        run: |
          rm -rf ${{ github.workspace }}/.lego
