name: Auto Renew and Deploy SSL Certificates

on:
  workflow_dispatch:
    inputs:
      dry_run:
        description: "Dry Run (true/false)"
        required: false
        default: "false"
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 10 */2 *" # 每两个月的第十天执行一次

permissions:
  contents: write

jobs:
  renew-deploy-cert:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Install uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
        with:
          enable-cache: true

      - name: Set up Python
        run: uv python install

      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@main

      - uses: tecolicom/actions-use-homebrew-tools@v1
        with:
          tools: lego

      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: Obtain and Upload certificates to Alibaba Cloud CDN
        env:
          ALIYUN_ACCESS_KEY_ID: ${{ secrets.ALIYUN_ACCESS_KEY_ID }}
          ALIYUN_ACCESS_KEY_SECRET: ${{ secrets.ALIYUN_ACCESS_KEY_SECRET }}
          # 设置阿里云cdn域名，一般是三级域名，例如cdn.example.com，多个域名以英文逗号隔开
          ALIYUN_CDN_DOMAINS: ${{ secrets.ALIYUN_CDN_DOMAINS }}
          WORKING_DIR: ${{ github.workspace }}
          EMAIL: ${{ secrets.EMAIL }}
          DRY_RUN: ${{ github.event.inputs.dry_run || 'false' }}

        run: uv run renew_and_deploy_certs.py

      - name: Clean up
        run: |
          rm -rf ${{ github.workspace }}/.lego
